# Generated by Django 6.0.6 on 2026-06-29 11:46

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankSampah",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nama", models.CharField(max_length=150)),
                ("alamat", models.TextField(blank=True)),
                ("kota", models.CharField(blank=True, max_length=100)),
                ("no_hp_pic", models.CharField(max_length=20)),
                ("wa_gateway_token", models.TextField(blank=True, null=True)),
                ("wa_template", models.TextField(blank=True)),
                ("foto_logo", models.CharField(blank=True, max_length=255)),
                ("foto_kegiatan", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("rejected", "Rejected"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("invite_token", models.CharField(blank=True, max_length=120)),
                ("invite_token_expires", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "bank_sampah",
                "ordering": ["nama"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "google_id",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nama", models.CharField(max_length=150)),
                ("no_hp", models.CharField(blank=True, max_length=20)),
                (
                    "jenis_kelamin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("laki-laki", "Laki-laki"),
                            ("perempuan", "Perempuan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tanggal_lahir", models.DateField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("pengelola", "Pengelola"),
                            ("superadmin", "Superadmin"),
                        ],
                        default="pengelola",
                        max_length=20,
                    ),
                ),
                ("is_profile_complete", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "bank_sampah",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="api.banksampah",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["nama"],
            },
        ),
        migrations.CreateModel(
            name="BankSampahApprovalLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=20,
                    ),
                ),
                ("catatan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_sampah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_logs",
                        to="api.banksampah",
                    ),
                ),
                (
                    "superadmin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bs_approval_log",
            },
        ),
        migrations.CreateModel(
            name="JenisSampah",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nomor", models.CharField(max_length=30)),
                ("nama_sampah", models.CharField(max_length=50)),
                (
                    "kategori",
                    models.CharField(
                        choices=[("organik", "Organik"), ("anorganik", "Anorganik")],
                        default="anorganik",
                        max_length=20,
                    ),
                ),
                ("deskripsi", models.TextField(blank=True)),
                ("harga_per_kg", models.DecimalField(decimal_places=2, max_digits=11)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_sampah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jenis_sampah",
                        to="api.banksampah",
                    ),
                ),
            ],
            options={
                "db_table": "jenis_sampah",
                "ordering": ["nomor"],
                "unique_together": {("bank_sampah", "nomor")},
            },
        ),
        migrations.CreateModel(
            name="Nasabah",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nomor", models.CharField(max_length=30)),
                ("nama", models.CharField(max_length=100)),
                (
                    "jenis_kelamin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("laki-laki", "Laki-laki"),
                            ("perempuan", "Perempuan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tanggal_lahir", models.DateField(blank=True, null=True)),
                ("alamat", models.TextField()),
                ("no_hp", models.CharField(max_length=20)),
                (
                    "tanggal_daftar",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bank_sampah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nasabah",
                        to="api.banksampah",
                    ),
                ),
            ],
            options={
                "db_table": "nasabah",
                "ordering": ["nomor"],
                "unique_together": {("bank_sampah", "no_hp"), ("bank_sampah", "nomor")},
            },
        ),
        migrations.CreateModel(
            name="Saldo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_saldo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nasabah",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saldo",
                        to="api.nasabah",
                    ),
                ),
            ],
            options={
                "db_table": "saldo",
            },
        ),
        migrations.CreateModel(
            name="Transaksi",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tanggal", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "total_nilai",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tipe",
                    models.CharField(
                        choices=[("setoran", "Setoran")],
                        default="setoran",
                        max_length=20,
                    ),
                ),
                ("catatan", models.TextField(blank=True, null=True)),
                (
                    "status_wa",
                    models.CharField(
                        choices=[
                            ("belum_dikirim", "Belum Dikirim"),
                            ("terkirim", "Terkirim"),
                            ("gagal", "Gagal"),
                        ],
                        default="belum_dikirim",
                        max_length=20,
                    ),
                ),
                (
                    "bank_sampah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaksi",
                        to="api.banksampah",
                    ),
                ),
                (
                    "dicatat_oleh",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaksi_dicatat",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nasabah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaksi",
                        to="api.nasabah",
                    ),
                ),
            ],
            options={
                "db_table": "transaksi",
                "ordering": ["-tanggal"],
            },
        ),
        migrations.CreateModel(
            name="DetailTransaksi",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nama_sampah_snapshot", models.CharField(max_length=50)),
                ("kategori_snapshot", models.CharField(max_length=20)),
                (
                    "harga_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=11),
                ),
                ("berat", models.DecimalField(decimal_places=3, max_digits=10)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "jenis_sampah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detail_transaksi",
                        to="api.jenissampah",
                    ),
                ),
                (
                    "transaksi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.transaksi",
                    ),
                ),
            ],
            options={
                "db_table": "detail_transaksi",
            },
        ),
    ]
