# Generated by Django 6.0.6 on 2026-06-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_primary_pengelola",
            field=models.BooleanField(default=False),
        ),
    ]
