# Generated by Django 6.0.6 on 2026-06-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_user_is_primary_pengelola"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banksampah",
            name="foto_kegiatan",
            field=models.FileField(blank=True, upload_to="bank_sampah/kegiatan/"),
        ),
        migrations.AlterField(
            model_name="jenissampah",
            name="kategori",
            field=models.CharField(
                choices=[
                    ("kertas", "Kertas"),
                    ("plastik", "Plastik"),
                    ("logam", "Logam"),
                    ("kaca", "Kaca"),
                    ("dll", "Dll"),
                    ("organik", "Organik"),
                    ("anorganik", "Anorganik"),
                ],
                default="plastik",
                max_length=20,
            ),
        ),
    ]
