# Generated by Django 6.0.6 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_banksampah_foto_kegiatan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banksampah",
            name="foto_logo",
            field=models.FileField(blank=True, upload_to="bank_sampah/logo/"),
        ),
    ]
