# Generated by Django 6.0.8 on 2026-09-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_banksampah_foto_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("pengelola", "Pengelola"),
                    ("pengelola_induk", "Pengelola Induk"),
                    ("superadmin", "Superadmin"),
                ],
                default="pengelola",
                max_length=20,
            ),
        ),
    ]
