# Generated by Django 6.0.8 on 2026-09-16 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_banksampah_banksampah_type_parent_consistent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nasabah",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="keanggotaan_nasabah",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
