# Generated by Django 6.0.8 on 2026-09-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_nasabah_nasabah_user_once_per_bank"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="alamat",
            field=models.TextField(blank=True),
        ),
    ]
