# Generated by Django 6.0.8 on 2026-09-20 06:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_nasabah_nasabah_user_once_per_bank"),
    ]

    operations = [
        migrations.AddField(
            model_name="nasabah",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="approved",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="NasabahApprovalLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")], max_length=20
                    ),
                ),
                ("catatan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "nasabah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_logs",
                        to="api.nasabah",
                    ),
                ),
                (
                    "pengurus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nasabah_approval_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "nasabah_approval_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
