# Generated by Django 6.0.8 on 2026-09-21 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_nasabah_status_nasabahapprovallog"),
        ("api", "0011_user_alamat"),
    ]

    operations = []
