# Generated by Django 6.0.8 on 2026-09-20 08:17

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_nasabah_status_nasabahapprovallog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pencairan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tanggal", models.DateTimeField(default=django.utils.timezone.now)),
                ("nominal", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "metode",
                    models.CharField(
                        choices=[("tunai", "Tunai"), ("transfer", "Transfer")], max_length=20
                    ),
                ),
                ("keterangan", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("tercatat", "Tercatat")], default="tercatat", max_length=20
                    ),
                ),
                ("saldo_sebelum", models.DecimalField(decimal_places=2, max_digits=14)),
                ("saldo_sesudah", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "bank_sampah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pencairan",
                        to="api.banksampah",
                    ),
                ),
                (
                    "dicatat_oleh",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pencairan_dicatat",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nasabah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pencairan",
                        to="api.nasabah",
                    ),
                ),
            ],
            options={
                "db_table": "pencairan",
                "ordering": ["-tanggal"],
                "indexes": [
                    models.Index(
                        fields=["bank_sampah", "nasabah", "tanggal"],
                        name="pencairan_bank_sa_bc7cf6_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("nominal__gt", 0)), name="pencairan_nominal_positive"
                    )
                ],
            },
        ),
    ]
