# Generated by Django 6.0.8 on 2026-09-26 02:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_nasabah_email"),
        ("api", "0011_nasabah_status_nasabahapprovallog"),
    ]

    operations = []
