# Generated by Django 6.0.8 on 2026-09-26 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_merge_nasabah_email_and_status"),
        ("api", "0012_pencairan"),
    ]

    operations = []
