# Generated by Django 6.0.8 on 2026-09-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_merge_20260921_1833"),
    ]

    operations = [
        migrations.AddField(
            model_name="nasabah",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
