# Generated by Django 6.0.8 on 2026-09-26 14:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_pencairan"),
    ]

    operations = [
        migrations.CreateModel(
            name="PencairanRevisi",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("versi", models.PositiveIntegerField()),
                ("tanggal", models.DateTimeField()),
                ("nominal", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "metode",
                    models.CharField(
                        choices=[("tunai", "Tunai"), ("transfer", "Transfer")], max_length=20
                    ),
                ),
                ("keterangan", models.TextField(blank=True)),
                ("saldo_sebelum", models.DecimalField(decimal_places=2, max_digits=14)),
                ("saldo_sesudah", models.DecimalField(decimal_places=2, max_digits=14)),
                ("alasan", models.CharField(max_length=255)),
                ("diubah_pada", models.DateTimeField(auto_now_add=True)),
                (
                    "diubah_oleh",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pencairan_revisi_dibuat",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pencairan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisi",
                        to="api.pencairan",
                    ),
                ),
            ],
            options={
                "db_table": "pencairan_revisi",
                "ordering": ["pencairan", "versi"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pencairan", "versi"), name="pencairan_revisi_unik"
                    )
                ],
            },
        ),
    ]
