# Generated by Django 6.0.8 on 2026-09-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_nasabah_email"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="nasabah",
            unique_together={("bank_sampah", "no_hp"), ("bank_sampah", "nomor")},
        ),
        migrations.AlterField(
            model_name="nasabah",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name="nasabah",
            unique_together={
                ("bank_sampah", "email"),
                ("bank_sampah", "no_hp"),
                ("bank_sampah", "nomor"),
            },
        ),
    ]
