# Generated by Django 6.0.8 on 2026-09-23 17:24

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def backfill_nasabah_email(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Fill blank/NULL Nasabah.email before the column becomes required.

    Rows written while the column was nullable (seeded fixtures, pengurus-
    entered rows created through the pre-PIL-204 serializer) still have
    NULL/"" here. Prefer the linked User's verified email when it is free
    within that bank; otherwise fall back to a synthetic address on the
    reserved .invalid TLD (RFC 2606) so it can never collide with, or be
    mistaken for, a real Google-verified email that _sync_nasabah_prefill
    links by.
    """
    Nasabah = apps.get_model("api", "Nasabah")

    for nasabah in Nasabah.objects.filter(
        models.Q(email__isnull=True) | models.Q(email="")
    ).iterator():
        candidate = ""
        linked_user = nasabah.user
        if linked_user is not None and linked_user.email:
            candidate = linked_user.email
            taken = (
                Nasabah.objects.filter(bank_sampah_id=nasabah.bank_sampah_id, email=candidate)
                .exclude(pk=nasabah.pk)
                .exists()
            )
            if taken:
                candidate = ""
        if not candidate:
            candidate = f"nasabah-{nasabah.pk}@pengguna.invalid"
        nasabah.email = candidate
        nasabah.save(update_fields=["email"])


class Migration(migrations.Migration):
    # Depends on both pre-existing sibling branches directly, rather than on
    # bare 0011_nasabah_email, so this migration is itself the single merge
    # point for alamat+status (0012_merge_20260921_1833) and
    # status+email+jadwal (0013_merge_nasabah_email_and_jadwal) ahead of
    # making Nasabah.email required. A prior version routed through separate
    # 0015/0016 merge migrations after this one; collapsing them here avoids
    # a migration-graph shape where Django's executor can reverse-migrate to
    # a target combination that silently drops the alamat/status columns or
    # skips reversing this migration (see api/test_migration_0014_email_backfill.py).
    dependencies = [
        ("api", "0012_merge_20260921_1833"),
        ("api", "0013_merge_nasabah_email_and_jadwal"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="nasabah",
            unique_together={("bank_sampah", "no_hp"), ("bank_sampah", "nomor")},
        ),
        migrations.AlterField(
            model_name="nasabah",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.RunPython(backfill_nasabah_email, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="nasabah",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name="nasabah",
            unique_together={
                ("bank_sampah", "email"),
                ("bank_sampah", "no_hp"),
                ("bank_sampah", "nomor"),
            },
        ),
    ]
