# Generated by Django 6.0.8 on 2026-09-25 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_merge_20260921_1833"),
        ("api", "0014_alter_nasabah_unique_together_alter_nasabah_email_and_more"),
    ]

    operations = []
