# Generated by Django 6.0.2 on 2026-09-27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_alter_nasabahapprovallog_pengurus_and_more"),
        ("api", "0016_merge_pil230_nasabah_stack"),
    ]

    operations = []
