# Generated by Django 6.0.8 on 2026-09-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_merge_pil225_and_pil232"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaksi",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
