# Generated by Django 6.0.8 on 2026-10-05 16:34

from typing import Any

from django.db import migrations, models
from django.db.migrations.state import StateApps


def backfill_nulls(apps: StateApps, schema_editor: Any) -> None:
    """S6553: nullable -> NOT NULL with "" default. Prod rows may hold NULLs;
    SET NOT NULL would fail on them, so map NULL to "" first."""
    BankSampah = apps.get_model("api", "BankSampah")
    Transaksi = apps.get_model("api", "Transaksi")
    BankSampah.objects.filter(wa_gateway_token__isnull=True).update(wa_gateway_token="")
    Transaksi.objects.filter(catatan__isnull=True).update(catatan="")
    Transaksi.objects.filter(idempotency_request_hash__isnull=True).update(
        idempotency_request_hash=""
    )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_idempotency_key_transaksi"),
    ]

    operations = [
        migrations.RunPython(backfill_nulls, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="banksampah",
            name="wa_gateway_token",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="transaksi",
            name="catatan",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="transaksi",
            name="idempotency_request_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
