# Generated by Django 6.0.8 on 2026-10-07 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_alter_banksampah_wa_gateway_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HargaSampah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("harga_per_kg", models.DecimalField(decimal_places=2, max_digits=11)),
                ("berlaku_mulai", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_sampah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="harga_sampah",
                        to="api.banksampah",
                    ),
                ),
                (
                    "dibuat_oleh",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="harga_sampah_dibuat",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jenis_sampah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="riwayat_harga",
                        to="api.jenissampah",
                    ),
                ),
            ],
            options={
                "db_table": "harga_sampah",
                "indexes": [
                    models.Index(
                        fields=["jenis_sampah", "berlaku_mulai"],
                        name="harga_sampa_jenis_s_fcad5a_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("harga_per_kg__gt", 0)),
                        name="harga_sampah_harga_positif",
                    )
                ],
            },
        ),
    ]
