# Generated by Django 6.0.8 on 2026-10-07 13:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_alter_banksampah_wa_gateway_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftPencairan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("nama", models.CharField(blank=True, max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("dikonfirmasi", "Dikonfirmasi"),
                            ("dibatalkan", "Dibatalkan"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "potongan_jenis",
                    models.CharField(
                        choices=[("persen", "Persen"), ("rupiah", "Rupiah")],
                        default="persen",
                        max_length=10,
                    ),
                ),
                ("potongan_nilai", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "bank_sampah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draft_pencairan",
                        to="api.banksampah",
                    ),
                ),
                (
                    "dibuat_oleh",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draft_pencairan_dibuat",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diubah_oleh",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draft_pencairan_diubah",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "draft_pencairan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DraftPencairanItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("nominal", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "metode",
                    models.CharField(
                        choices=[("tunai", "Tunai"), ("transfer", "Transfer")],
                        default="tunai",
                        max_length=20,
                    ),
                ),
                (
                    "potongan_jenis",
                    models.CharField(
                        blank=True,
                        choices=[("persen", "Persen"), ("rupiah", "Rupiah")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "potongan_nilai",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.draftpencairan",
                    ),
                ),
                (
                    "nasabah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draft_pencairan_item",
                        to="api.nasabah",
                    ),
                ),
            ],
            options={
                "db_table": "draft_pencairan_item",
                "ordering": ["nasabah__nama", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("draft", "nasabah"), name="draft_item_nasabah_unik"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("nominal__gt", 0)), name="draft_item_nominal_positive"
                    ),
                ],
            },
        ),
    ]
