# Generated by Django 6.0.8 on 2026-10-07 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_draft_pencairan"),
    ]

    operations = [
        migrations.AddField(
            model_name="pencairan",
            name="draft",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pencairan",
                to="api.draftpencairan",
            ),
        ),
        migrations.AddField(
            model_name="pencairan",
            name="potongan",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddConstraint(
            model_name="pencairan",
            constraint=models.CheckConstraint(
                condition=models.Q(("potongan__gte", 0), ("potongan__lte", models.F("nominal"))),
                name="pencairan_potongan_within_nominal",
            ),
        ),
    ]
