# Generated by Django 6.0.8 on 2026-10-10 08:12

from django.db import migrations, models


def isi_saldo_draft_terkonfirmasi(apps, schema_editor):  # type: ignore[no-untyped-def]
    """Drafts paid before this column existed: the pencairan they wrote kept the saldo."""
    Item = apps.get_model("api", "DraftPencairanItem")
    Pencairan = apps.get_model("api", "Pencairan")
    for item in Item.objects.filter(draft__status="dikonfirmasi", saldo_sebelum__isnull=True):
        cair = Pencairan.objects.filter(draft_id=item.draft_id, nasabah_id=item.nasabah_id).first()
        if cair is not None:
            Item.objects.filter(pk=item.pk).update(saldo_sebelum=cair.saldo_sebelum)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_pencairan_potongan_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftpencairanitem",
            name="saldo_sebelum",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.RunPython(isi_saldo_draft_terkonfirmasi, migrations.RunPython.noop),
    ]
