# Generated by Django 6.0.8 on 2026-10-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_draft_item_saldo_sebelum"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftpencairan",
            name="jumlah_jenis",
            field=models.CharField(
                blank=True,
                choices=[("persen", "Persen"), ("rupiah", "Rupiah")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="draftpencairan",
            name="jumlah_nilai",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
